import test from 'node:test';
import assert from 'node:assert/strict';
import { handlePublisherRoute, handlePublisherReleaseRoute, validPurchase } from '../worker/src/publisher.js';
const sid='cs_live_1234567890ABC',price='price_approved';
const session={id:sid,mode:'payment',status:'complete',payment_status:'paid',livemode:true,currency:'eur',amount_total:1900,amount_subtotal:1900,automatic_tax:{enabled:true,status:'complete'}};
const items={has_more:false,data:[{quantity:1,price:{id:price,currency:'eur',unit_amount:1900,tax_behavior:'inclusive',livemode:true}}]};
const expected={sid,price,live:true};
function fixture(s=session,i=items) {const calls=[];const env={ALLOWED_ORIGINS:'arling.sk',PUBLISHER_RELEASE_SHA256:'a'.repeat(64),PUBLISHER_LIVE_PRICE:price,STRIPE_SECRET_KEY:'fixture',ASISTENT_CACHE:{get:async()=>null,put:async()=>{}},KONTROLA:{get:async()=>new Uint8Array([80,75,3,4]).buffer},fetchImpl:async(url)=>{calls.push(url);return Response.json(url.includes('/line_items')?i:s);}};return {env,calls};}
const req=(id=sid,path='download')=>new Request('https://api.example/v1/publisher/'+path+'?session_id='+id,{headers:{Origin:'https://arling.sk'}});
test('only exact paid inclusive single-item purchase is valid',()=>assert.equal(validPurchase(session,items,expected),true));
for(const [name,change] of Object.entries({unpaid:{payment_status:'unpaid'},pending:{status:'open'},foreignCurrency:{currency:'usd'},wrongTotal:{amount_total:1901},wrongId:{id:'cs_live_other'},testAsLive:{livemode:false},missingTax:{automatic_tax:null}}))test(name+' rejected',()=>assert.equal(validPurchase({...session,...change},items,expected),false));
for(const [name,modified] of Object.entries({otherProduct:{...items,data:[{...items.data[0],price:{...items.data[0].price,id:'price_other'}}]},extraItem:{...items,data:[...items.data,...items.data]},pagination:{...items,has_more:true},twoCopies:{...items,data:[{...items.data[0],quantity:2}]},exclusive:{...items,data:[{...items.data[0],price:{...items.data[0].price,tax_behavior:'exclusive'}}]}}))test(name+' rejected',()=>assert.equal(validPurchase(session,modified,expected),false));
test('download checks Stripe session and line items; no public static URL',async()=>{const {env,calls}=fixture();const r=await handlePublisherRoute(req(),env);assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'application/zip');assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(calls.length,2);assert.deepEqual([...new Uint8Array(await r.arrayBuffer())],[80,75,3,4]);});
test('status reports readiness after same verification',async()=>{const {env}=fixture();const r=await handlePublisherRoute(req(sid,'status'),env);assert.deepEqual(await r.json(),{paid:true,pack:'slitherlink-pattern-01',livemode:true,ready:true});});
test('malformed session never calls Stripe',async()=>{const {env,calls}=fixture();assert.equal((await handlePublisherRoute(req('../evil'),env)).status,400);assert.equal(calls.length,0);});
test('test mode cannot be enabled by client',async()=>{const {env,calls}=fixture();assert.equal((await handlePublisherRoute(req('cs_test_1234567890'),env)).status,403);assert.equal(calls.length,0);});
test('Stripe network failure is closed',async()=>{const {env}=fixture();env.fetchImpl=async()=>{throw new Error('offline');};assert.equal((await handlePublisherRoute(req(),env)).status,503);});
test('paid unrelated product cannot read KV',async()=>{const {env}=fixture(session,{...items,data:[{...items.data[0],price:{...items.data[0].price,id:'price_unrelated'}}]});env.KONTROLA.get=async()=>{throw new Error('must not read');};assert.equal((await handlePublisherRoute(req(),env)).status,402);});
test('missing release fails closed',async()=>{const {env}=fixture();env.KONTROLA.get=async()=>null;assert.equal((await handlePublisherRoute(req(),env)).status,503);});
test('release upload requires existing admin token',async()=>{const {env}=fixture();assert.equal((await handlePublisherReleaseRoute(new Request('https://api.example/v1/publisher/admin/release',{method:'PUT',body:'anything'}),env)).status,401);});
test('release upload requires exact approved hash and is idempotent',async()=>{const {env}=fixture();env.ADMIN_TOKEN='admin-fixture';const body=new Uint8Array(30);body.set([80,75,3,4]);env.PUBLISHER_RELEASE_SHA256=Buffer.from(await crypto.subtle.digest('SHA-256',body)).toString('hex');let writes=0;env.KONTROLA.put=async()=>{writes++;};const put=()=>new Request('https://api.example/v1/publisher/admin/release',{method:'PUT',headers:{'X-Admin-Token':'admin-fixture'},body});assert.equal((await handlePublisherReleaseRoute(put(),env)).status,200);assert.equal((await handlePublisherReleaseRoute(put(),env)).status,200);assert.equal(writes,2);env.PUBLISHER_RELEASE_SHA256='a'.repeat(64);assert.equal((await handlePublisherReleaseRoute(put(),env)).status,409);assert.equal(writes,2);});

test('malformed Stripe items fail closed',()=>assert.equal(validPurchase(session,{has_more:false},expected),false));
test('expired admin test window rejects test session without Stripe',async()=>{const {env,calls}=fixture();env.PUBLISHER_TEST_ENABLED='1';env.KONTROLA.get=async()=>String(Date.now()-100);assert.equal((await handlePublisherRoute(req('cs_test_1234567890'),env)).status,403);assert.equal(calls.length,0);});
test('explicit temporary test window verifies sandbox objects with test key',async()=>{const testSid='cs_test_1234567890';const {env,calls}=fixture({...session,id:testSid,livemode:false},{...items,data:[{...items.data[0],price:{...items.data[0].price,livemode:false}}]});env.PUBLISHER_TEST_ENABLED='1';env.PUBLISHER_TEST_PRICE=price;env.STRIPE_TEST_SECRET_KEY='fixture-test';env.KONTROLA.get=async(k)=>k.endsWith('/test-until')?String(Date.now()+60000):new Uint8Array([80,75,3,4]).buffer;assert.equal((await handlePublisherRoute(req(testSid),env)).status,200);assert.equal(calls.length,2);});
